var DATA = [
{
	title: 'Posts About Important Things',
	headerColor: 'hsl(175, 30%, 30%)',
	sidebarColor: 'hsl(175, 20%, 10%)',
	contentColor: 'hsl(175, 20%, 90%)',
	posts: [
	{
		title: 'ok this time im really gonna starting',
		date: 'Dec. 10, 2016',
		content: 'Bacon ipsum dolor amet ut sint sed ut bacon. Nulla picanha ex turkey shankle hamburger nostrud. Chicken cupim pork loin filet mignon dolor, ut tail irure esse. Beef short loin ex kevin shoulder aliquip in voluptate shankle prosciutto ribeye quis sunt swine non. Kevin filet mignon nostrud, magna prosciutto nulla ad shoulder short ribs pork loin doner consectetur ham hock corned beef. Dolore strip steak qui ham hock in, chuck rump swine shankle. Bacon pork belly quis ut. Eiusmod dolor fatback pork loin ex. Jerky tri-tip landjaeger meatball lorem dolore. Spare ribs t-bone fugiat, dolore leberkas porchetta sint shankle mollit hamburger ribeye andouille. Ea tri-tip shankle adipisicing, nisi laboris quis et strip steak. Fatback velit ea, shank minim do lorem dolore veniam consectetur swine spare ribs sed. Filet mignon ut in alcatra. Ad t-bone rump, dolore dolore enim landjaeger deserunt nisi pastrami jowl pork loin voluptate cow. Tri-tip prosciutto aliqua proident adipisicing ullamco labore. Incididunt filet mignon aliqua swine, aliquip labore shank short ribs qui commodo sed do consequat sunt. Spare ribs kielbasa dolor pork chop sed do. Minim sausage pork chop enim, magna et eu cow beef ribs meatloaf ground round. Rump qui capicola shank shoulder ullamco ad. Pork belly tongue laborum fugiat, in brisket dolor cupidatat ham hock deserunt. Shank dolore chuck voluptate elit enim ground round. Corned beef sint kevin eu landjaeger pork chop, shoulder pariatur sausage. Beef ribs pork chop ball tip reprehenderit porchetta est frankfurter. Cupim fugiat shankle pastrami excepteur picanha prosciutto ball tip. Id shank reprehenderit, tri-tip boudin lorem magna esse sirloin aliquip shankle et andouille pig cupidatat. Deserunt in eiusmod, consequat in ball tip landjaeger shankle meatball frankfurter pork capicola ad. Does your lorem ipsum text long for something a little meatier? Give our generator a try… it’s tasty! '
	},
	{
		title: 'Whoops... forgot to blog',
		date: 'June 1st, 2016',
		content: 'Bacon ipsum dolor amet alcatra eu beef labore, veniam esse in. Minim elit kielbasa laboris. Alcatra pancetta tail shankle jerky tri-tip, dolore andouille porchetta cupim bresaola spare ribs sint capicola sunt. Jerky mollit esse, adipisicing deserunt t-bone culpa duis bacon ut pancetta beef. Corned beef shoulder velit ham sunt tempor, shankle frankfurter aliquip qui jerky reprehenderit andouille porchetta pancetta. Qui short ribs cow beef. Exercitation consequat leberkas beef velit incididunt jowl ball tip meatloaf, pastrami labore eiusmod turducken aliquip pork chop. Fugiat commodo tempor shankle cupidatat incididunt swine dolore andouille reprehenderit capicola anim tri-tip pariatur meatloaf. Turkey ut kevin pork loin. Brisket qui commodo, aute excepteur culpa sed bacon. Bacon fatback cow, landjaeger pastrami cillum duis boudin lorem drumstick pariatur ea tenderloin excepteur. Veniam tenderloin et pastrami, ad biltong adipisicing hamburger. In adipisicing id, ut culpa drumstick elit pig consequat dolor lorem shoulder veniam.'
	},
	{
		title: 'Still goin Strong!',
		date: 'Jan. 3rd 2016',
		content: 'Bacon ipsum dolor amet alcatra eu beef labore, veniam esse in. Minim elit kielbasa laboris. Alcatra pancetta tail shankle jerky tri-tip, dolore andouille porchetta cupim bresaola spare ribs sint capicola sunt. Jerky mollit esse, adipisicing deserunt t-bone culpa duis bacon ut pancetta beef. Corned beef shoulder velit ham sunt tempor, shankle frankfurter aliquip qui jerky reprehenderit andouille porchetta pancetta. Qui short ribs cow beef. Exercitation consequat leberkas beef velit incididunt jowl ball tip meatloaf, pastrami labore eiusmod turducken aliquip pork chop. Fugiat commodo tempor shankle cupidatat incididunt swine dolore andouille reprehenderit capicola anim tri-tip pariatur meatloaf. Turkey ut kevin pork loin. Brisket qui commodo, aute excepteur culpa sed bacon. Bacon fatback cow, landjaeger pastrami cillum duis boudin lorem drumstick pariatur ea tenderloin excepteur. Veniam tenderloin et pastrami, ad biltong adipisicing hamburger. In adipisicing id, ut culpa drumstick elit pig consequat dolor lorem shoulder veniam.'
	},
	{
		title: 'Crazy things!!',
		date: 'Jan. 2nd 2016',
		content: 'Bacon ipsum dolor amet ut sint sed ut bacon. Nulla picanha ex turkey shankle hamburger nostrud. Chicken cupim pork loin filet mignon dolor, ut tail irure esse. Beef short loin ex kevin shoulder aliquip in voluptate shankle prosciutto ribeye quis sunt swine non. Kevin filet mignon nostrud, magna prosciutto nulla ad shoulder short ribs pork loin doner consectetur ham hock corned beef. Dolore strip steak qui ham hock in, chuck rump swine shankle. Bacon pork belly quis ut. Eiusmod dolor fatback pork loin ex. Jerky tri-tip landjaeger meatball lorem dolore. Spare ribs t-bone fugiat, dolore leberkas porchetta sint shankle mollit hamburger ribeye andouille. Ea tri-tip shankle adipisicing, nisi laboris quis et strip steak. Fatback velit ea, shank minim do lorem dolore veniam consectetur swine spare ribs sed. Filet mignon ut in alcatra. Ad t-bone rump, dolore dolore enim landjaeger deserunt nisi pastrami jowl pork loin voluptate cow. Tri-tip prosciutto aliqua proident adipisicing ullamco labore. Incididunt filet mignon aliqua swine, aliquip labore shank short ribs qui commodo sed do consequat sunt. Spare ribs kielbasa dolor pork chop sed do. Minim sausage pork chop enim, magna et eu cow beef ribs meatloaf ground round. Rump qui capicola shank shoulder ullamco ad. Pork belly tongue laborum fugiat, in brisket dolor cupidatat ham hock deserunt. Shank dolore chuck voluptate elit enim ground round. Corned beef sint kevin eu landjaeger pork chop, shoulder pariatur sausage. Beef ribs pork chop ball tip reprehenderit porchetta est frankfurter. Cupim fugiat shankle pastrami excepteur picanha prosciutto ball tip. Id shank reprehenderit, tri-tip boudin lorem magna esse sirloin aliquip shankle et andouille pig cupidatat. Deserunt in eiusmod, consequat in ball tip landjaeger shankle meatball frankfurter pork capicola ad. Does your lorem ipsum text long for something a little meatier? Give our generator a try… it’s tasty! '
	},
	{
		title: 'First Post!!!',
		date: 'Jan. 1st, 2016',
		content: 'Bacon ipsum dolor amet ut sint sed ut bacon. Nulla picanha ex turkey shankle hamburger nostrud. Chicken cupim pork loin filet mignon dolor, ut tail irure esse. Beef short loin ex kevin shoulder aliquip in voluptate shankle prosciutto ribeye quis sunt swine non. Kevin filet mignon nostrud, magna prosciutto nulla ad shoulder short ribs pork loin doner consectetur ham hock corned beef. Dolore strip steak qui ham hock in, chuck rump swine shankle. Bacon pork belly quis ut. Eiusmod dolor fatback pork loin ex. Jerky tri-tip landjaeger meatball lorem dolore. Spare ribs t-bone fugiat, dolore leberkas porchetta sint shankle mollit hamburger ribeye andouille. Ea tri-tip shankle adipisicing, nisi laboris quis et strip steak. Fatback velit ea, shank minim do lorem dolore veniam consectetur swine spare ribs sed. Filet mignon ut in alcatra. Ad t-bone rump, dolore dolore enim landjaeger deserunt nisi pastrami jowl pork loin voluptate cow. Tri-tip prosciutto aliqua proident adipisicing ullamco labore. Incididunt filet mignon aliqua swine, aliquip labore shank short ribs qui commodo sed do consequat sunt. Spare ribs kielbasa dolor pork chop sed do. Minim sausage pork chop enim, magna et eu cow beef ribs meatloaf ground round. Rump qui capicola shank shoulder ullamco ad. Pork belly tongue laborum fugiat, in brisket dolor cupidatat ham hock deserunt. Shank dolore chuck voluptate elit enim ground round. Corned beef sint kevin eu landjaeger pork chop, shoulder pariatur sausage. Beef ribs pork chop ball tip reprehenderit porchetta est frankfurter. Cupim fugiat shankle pastrami excepteur picanha prosciutto ball tip. Id shank reprehenderit, tri-tip boudin lorem magna esse sirloin aliquip shankle et andouille pig cupidatat. Deserunt in eiusmod, consequat in ball tip landjaeger shankle meatball frankfurter pork capicola ad. Does your lorem ipsum text long for something a little meatier? Give our generator a try… it’s tasty! '
	}
	]
}]